export const SET_MOST_VISITED_SITES="SET_MOST_VISITED_SITES";
export const SET_BOOKMARKS="SET_BOOKMARKS";
export const SET_BOOKMARK_PREVIEW="SET_BOOKMARK_PREVIEW";
export const FAILED_TO_SET_BOOKMARK_PREVIEW="FAILED_TO_SET_BOOKMARK_PREVIEW";