export const SET_MOST_VISITED_SITES = "SET_MOST_VISITED_SITES";
export const SET_BOOKMARKS = "SET_BOOKMARKS";
export const SET_RECENT_BOOKMARKS = "SET_RECENT_BOOKMARKS";
export const SET_BOOKMARK_PREVIEW = "SET_BOOKMARK_PREVIEW";
export const FAILED_TO_SET_BOOKMARK_PREVIEW = "FAILED_TO_SET_BOOKMARK_PREVIEW";
export const SET_BOOKMARK_FOLDERS = "SET_BOOKMARK_FOLDERS";
export const SET_SEARCH_ACTIVE = "SET_SEARCH_ACTIVE";
export const SET_SEARCHED_TERM = "SET_SEARCHED_TERM";
export const SET_SELECTED_FOLDER = "SET_SELECTED_FOLDER";
export const OPEN_CLOSE_DROPDOWN_OPEN = "OPEN_CLOSE_DROPDOWN_OPEN";
export const SET_FILTERED_BOOKMARKS = "SET_FILTERED_BOOKMARKS";
export const SET_COLORS_MAP = "SET_COLORS_MAP";

export const GOT_IMAGES_SUCCESSFULLY = "GOT_IMAGES_SUCCESSFULLY";
export const FAILED_TO_GET_IMAGES = "FAILED_TO_GET_IMAGES";

export const SAVED_URLS_SUCCESSFULLY = "SAVED_URLS_SUCCESSFULLY";
export const SAVED_URLS_FAILED = "SAVED_URLS_FAILED";

export const UPDATE_BOOKMARK = "UPDATE_BOOKMARK";